### ISSUE TITLE
Icons for tracks not visible

### ISSUE THREAD

**Issue by blueelvis** [exercism/gui#55]
I just started the GUI, turned on Dev Tools and found that the URL to fetch for icon is wrong.

*Error* - 
`    http://exercism.io/img/tracks/cpp.png Failed to load resource: the server responded with a status of 404 
    (Not Found)
`
The actual URL (which I fetched from the website is - http://exercism.io/tracks/cpp/icon

**Comment by holandes22** [comment]
@blueelvis my guess is you are using version 0.2.0 right?
The icon URLs were changed at some point which broke that version. I fixed it the 0.3.0 version. 
If you are on Linux or Mac you can try the latest one https://github.com/exercism/gui/releases/tag/v0.3.1
that release is still tagged as `pre-release` since there is a problem in appveyor building the Windows version which I couldn't figure out yet.

**Comment by holandes22** [comment]
v0.4.0 fixed the windows installer in case you need it. Closing this as it was fixed in 0.3.0
