### ISSUE TITLE
Indication of current problem in progress

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/gui#56]
I've started testing the gui, and I think there's a lot of good potential. However, one thing that I noticed right away was that there was no indication as to which exercise I was currently working on. It can get hard to keep track of when you've submitted a fair amount of problems, and the `Get status` section doesn't help with that. The `Fetch latest` button will notify me which files remain unchanged because I currently have a problem checked out that I haven't submitted yet, but that seems fairly unintuitive (especially for newcomers).

Would it be a potential candidate to be the second entry in the `Links` list?

**Comment by holandes22** [comment]
Hi, thank you for the feedback!

It would indeed be a very helpful addition, but I'm not quite sure how to implement this.
The problem is that is hard to find the info to correctly indicate the current problem being worked on. I believe The API indicates what is the next problem after you submitted one (not entirely sure about this) but that might not be accurate as you could still be working on another iteration of the same problem (or maybe even revisiting old ones).
With the CLI you might make an educated guess based on the current directory, but there is none of that with the GUI as it is launched globally.

It is a nice feature, so I want to add it, just need to think how to make it work
